StackWithMax
tarstars/algo_club pull request #24
Opened 2020-03-27 23:00 UTC by chebotaralexei

Implementation with an additional array

2020-03-28 05:54 UTC, tarstars requested changes
Круто! У меня скорее вопросы по Java, чем замечания. Ещё немного потуплю над логикой массива максимумов в стэке, попытаюсь придумать контрпример. Но кажется, что ты роскошно реализовал свою клёвую идею :)

2020-03-28 05:54 UTC, tarstars commented on sandbox/users/chebotar/src/Stack.java
> +    public Stack(final int maxSize, final int... values) {
Это не замечание, а вопрос: что эти три точки делают? :)

2020-03-28 05:54 UTC, tarstars commented on sandbox/users/chebotar/src/Stack.java
> +    public void push(int i) {
Название переменной выбивается из общего фона. Вокруг всё такое подробное и вдруг i...

2020-03-29 01:33 UTC, chebotaralexei commented on sandbox/users/chebotar/src/Stack.java
> +    public Stack(final int maxSize, final int... values) {
Это vararg в джаве. Собирает значения поданные через запятую в массив
Аргумент VarArgs должен стоять последним в списке аргументов, то есть после него не может быть ни одного аргумента, но перед ним сколько угодно
Внутри метода мы работаем с VarArgs как с массивом

2020-03-29 01:34 UTC, chebotaralexei commented on sandbox/users/chebotar/src/Stack.java
> +    public void push(int i) {
Ага, поправлю

2020-04-04 09:10 UTC, merged