Matrix Multiplication
tarstars/algo_club pull request #27
Opened 2020-04-17 00:46 UTC by DilemmaLab

2020-04-17 01:01 UTC, tarstars requested changes

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +  /*int *p1 = memcpy(malloc(sizeof *p1 * h1 * w1),
Если этот код не нужен, сотри комментарии. Если нужен - оформи в виде функции, которую можно вызывать в случае нужды.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +  // int* p1 = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
Код не нужен - удали. Нужен - оформи в виде функции.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +    for (int q = p*w1; q < w1*(p+1); ++q) {
Это неправильная логика использования q. Смысл q - индекс элемента в матрице. Он больше либо равен нуля и меньше ширины матрицы. Здесь это утверждение нарушается. Я понимаю, что ты эту формулу вывела на листочке и она для тебя важна. Но нужно выбрать один из двух вариантов: либо эта переменная q, и у неё смысл горизонтального индекса в матрице. Либо это что-то другое. Тогда эту переменную нужно переназвать, придумав ей хорошее длинное говорящее имя.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +      printf("%d ", p1[q*w1 + p]);
Да, норм. Это хорошо.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +  /*p2[0] =  11;  p2[1] = 12;  p2[2] = 13;  p2[3] = 14;  p2[4] = 15;
Либо удалить, либо оформить в виде функции.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +  // p2 = {1, 1, 1, 1, 1, 1, 1, 1};
Либо удалить, либо оформить в виде функции.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +      //p2[p*w2 + q] = 1;
Это нужно? Не нужно - удаляем

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +            ///////printf("%d*%d+", p1[p*w1 + r], p2[r*w2 + q]); // p2[r*w2 + q]
Не должно оставатьс таких страшных комментариев в коде.

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +  for (int p = 0; p < h1; ++p) { // w2 != h1
Почему w2 != h1 ?  Это общее правило, так будет всегда?

2020-04-17 01:01 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +
Чего-то тут не хватает. То, до чего ты догадалась, но в программу не вписала.

2020-04-21 00:04 UTC, DilemmaLab commented on sandbox/users/dilemma/matrix_multiplication.c
> +
Пока не могу вспомнить.

2020-04-21 06:13 UTC, tarstars commented on sandbox/users/dilemma/matrix_multiplication.c
> +
Три недели назад в телеграм-чате @workAccount ты написала ответ на этот вопрос.

2020-04-21 12:40 UTC, tarstars approved these changes

2020-04-21 12:40 UTC, merged