My stack and queue realization
tarstars/algo_club pull request #28
Opened 2020-04-30 08:21 UTC by rumary

2020-05-06 13:14 UTC, tarstars requested changes

2020-05-06 13:14 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +            return self.stack_pop.pop()
Просто удалить строчку? Меньше кода - меньше проблем?

2020-05-06 13:14 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +            while self.stack_push.size() != 0:
Где-то этот код я уже видел. Может, вынесем в функцию?

2020-05-06 13:14 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +        return max(self.stack_pop.max(), self.stack_push.max())
Всегда ли можно max() посчитать для стэка, когда его можно посчитать для очереди? Аккуратнее.

2020-05-06 13:14 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +    unittest.main()
Файл заканчиваем пустой строчкой

2020-05-08 22:55 UTC, rumary commented on sandbox/users/rumary/queue_2_stacks.py
> +            return self.stack_pop.pop()
Удалила)

2020-05-08 22:55 UTC, rumary commented on sandbox/users/rumary/queue_2_stacks.py
> +            while self.stack_push.size() != 0:
Вынесла)

2020-05-08 22:56 UTC, rumary commented on sandbox/users/rumary/queue_2_stacks.py
> +        return max(self.stack_pop.max(), self.stack_push.max())
Поправила, теперь, кажется, работает)

2020-05-08 22:56 UTC, rumary commented on sandbox/users/rumary/queue_2_stacks.py
> +    unittest.main()
done

2020-05-10 19:31 UTC, rumary commented
@tarstars ошибки поправила)

2020-05-11 20:51 UTC, rumary commented
Add solution for Array Rotation

2020-05-23 08:34 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +        return max(self.stack_pop.max(), self.stack_push.max())
Ура!

2020-05-23 08:41 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +    def max(self):
Кажется, с таким тесткейсом могут быть проблемы:

s = Queue(10)
s.enqueue(-1)
s.enqueue(-2)
s.dequeue()
self.assertEqual(-2, s.max())

2020-05-23 08:42 UTC, tarstars requested changes
Check testcase

2020-05-24 12:42 UTC, rumary commented on sandbox/users/rumary/queue_2_stacks.py
> +    def max(self):
Fix)

2020-05-24 13:09 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +    def max(self):
А это действительно фикс? Если у тебя один стек пустой, его max вернёт None, и этот None будет сравниваться со значением, которое вернул другой max. Я когда попробовал посчитать max(5, None) у меня получилось

TypeError: '>' not supported between instances of 'int' and 'NoneType'

Или я чего-то не понимаю? :)

2020-05-24 13:12 UTC, tarstars commented on sandbox/users/rumary/queue_2_stacks.py
> +    def max(self):
Не, теперь всё норм. Я не там читал :)

2020-05-24 13:13 UTC, merged